
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Template to deploy a sample application

Parameters:
  ALBVpcId:
    Type: String
  ALBSecurityGroup:
    Type: String
  ALBSubnetA:
    Type: String
  ALBSubnetB:
    Type: String

Resources:
  SimpleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Timeout: 200
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DataBucket

  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - !Ref ALBSubnetA
        - !Ref ALBSubnetB

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LambdaTargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  # LoadBalancerListenerRulePost:
  #   Type: AWS::ElasticLoadBalancingV2::ListenerRule
  #   Properties:
  #     Actions:
  #       - Type: forward
  #         TargetGroupArn: !Ref PostLambdaTargetGroup
  #     Conditions:
  #       - Field: http-request-method
  #       HttpRequestMethodConfig:
  #         Values:
  #           - POST
  #     LoadBalancerArn: !Ref LoadBalancer
  #     Priority: 1

  LambdaTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: True
      TargetType: lambda
      Targets:
        - Id: !GetAtt [ SimpleFunction, Arn ]

  SimpleFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SimpleFunction
      Action: 'lambda:InvokeFunction'
      Principal: elasticloadbalancing.amazonaws.com

Outputs:
  InvokeURL:
    Description: URL to invoke Lambda
    Value: !GetAtt [ LoadBalancer, DNSName ]
